FROM alpine

EXPOSE 8080
RUN apk add git
RUN apk add nginx

RUN cd /home
RUN git clone https://github.com/ReEngine/Minikube-test.git /home/files
COPY src/nginx/nginx.conf /etc/nginx/
CMD ["nginx", "-g", "daemon off;"]