FROM alpine

RUN apk add --no-cache git nginx
RUN mkdir -p /home/files
RUN cd /home && git clone https://github.com/ReEngine/Minikube-test.git /home/files
COPY src/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]