apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31002
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}